version: '3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: tomgll/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
      - docs:/app/docs/
    depends_on:
     - db

  frontend:
    env_file: .env
    image: tomgll/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: tomgll/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
      - frontend
