version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    build: ./backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  
  frontend:
    container_name: foodgram-front
    build: ./frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
