# Generated by Django 3.2.3 on 2025-04-03 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250401_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping_list', 'verbose_name': 'Список покупок'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество ингредиента не может быть меньше 1 или больше 10000'), django.core.validators.MaxValueValidator(limit_value=10000, message='Количество ингредиента не может быть меньше 1 или больше 10000')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления не может быть меньше 1 или больше 3600'), django.core.validators.MaxValueValidator(limit_value=3600, message='Время приготовления не может быть меньше 1 или больше 3600')]),
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
